name: ippbxpy
version: 'latest'
summary: Script for asterisk and Yealink configuration
description: TBD

grade: stable
confinement: classic

apps:
  ippbxpy:
    command: ippbxpy

parts:
  ippbxpy:
    source: https://github.com/v12aml/ippbx.py.git
    plugin: python
    python-version: 'python3'
