name: ippbx.py
version: 'latest'
summary: Script for asterisk and Yealink configuration
description: TBD

grade: stable
confinement: classic

apps:
  asciinema:
    command: asciinema

parts:
  asciinema:
    source: https://github.com/v12aml/ippbx.py.git
    plugin: python
    python-version: 'python3'
